### YamlMime:JavaMember
uid: "com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner.withException*"
fullName: "com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner.withException"
name: "withException"
nameWithType: "SourceControlSyncJobByIdInner.withException"
members:
- uid: "com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner.withException(java.lang.String)"
  fullName: "com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner.withException(String exception)"
  name: "withException(String exception)"
  nameWithType: "SourceControlSyncJobByIdInner.withException(String exception)"
  summary: "Set the exception property: The exceptions that occurred while running the sync job."
  parameters:
  - description: "the exception value to set."
    name: "exception"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public SourceControlSyncJobByIdInner withException(String exception)"
  returns:
    description: "the SourceControlSyncJobByIdInner object itself."
    type: "<xref href=\"com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner?alt=com.azure.resourcemanager.automation.fluent.models.SourceControlSyncJobByIdInner&text=SourceControlSyncJobByIdInner\" data-throw-if-not-resolved=\"False\" />"
type: "method"
metadata: {}
package: "com.azure.resourcemanager.automation.fluent.models"
artifact: com.azure.resourcemanager:azure-resourcemanager-automation:1.0.0-beta.1
