### YamlMime:ManagedReference
items:
- uid: com.azure.core.exception
  id: exception
  children:
  - com.azure.core.exception.AzureException
  - com.azure.core.exception.ClientAuthenticationException
  - com.azure.core.exception.DecodeException
  - com.azure.core.exception.HttpRequestException
  - com.azure.core.exception.HttpResponseException
  - com.azure.core.exception.ResourceExistsException
  - com.azure.core.exception.ResourceModifiedException
  - com.azure.core.exception.ResourceNotFoundException
  - com.azure.core.exception.ServiceResponseException
  - com.azure.core.exception.TooManyRedirectsException
  href: com.azure.core.exception.yml
  langs:
  - java
  name: com.azure.core.exception
  nameWithType: com.azure.core.exception
  fullName: com.azure.core.exception
  type: Namespace
  source:
    remote:
      path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: sdk/core/azure-core/src/main/java/com/azure/core/exception/AzureException.java
    startLine: 3
  summary: "<p>Package containing core exception classes </p>"
  syntax:
    content: package com.azure.core.exception
references:
- uid: com.azure.core.exception.AzureException
  parent: com.azure.core.exception
  href: com.azure.core.exception.AzureException.yml
  name: AzureException
  nameWithType: AzureException
  fullName: com.azure.core.exception.AzureException
  type: Class
  summary: "<p>The base exception type for all Azure-related exceptions.</p>\r\n<p></p>"
  syntax:
    content: public class AzureException
- uid: com.azure.core.exception.ClientAuthenticationException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ClientAuthenticationException.yml
  name: ClientAuthenticationException
  nameWithType: ClientAuthenticationException
  fullName: com.azure.core.exception.ClientAuthenticationException
  type: Class
  summary: "<p>The exception thrown when failed to authenticate the client request with status code of 4XX, typically 401 unauthorized.</p>\r\n<p>A runtime exception indicating request authorization failure caused by one of the following scenarios: A client did not send the required authorization credentials to access the requested resource, i.e. Authorization HTTP header is missing in the request, OR - In case the request already contains the HTTP Authorization header - then the exception indicates that authorization has been refused for the credentials contained in the request header. </p>"
  syntax:
    content: public class ClientAuthenticationException extends HttpResponseException
- uid: com.azure.core.exception.DecodeException
  parent: com.azure.core.exception
  href: com.azure.core.exception.DecodeException.yml
  name: DecodeException
  nameWithType: DecodeException
  fullName: com.azure.core.exception.DecodeException
  type: Class
  summary: "<p>Error raised during response deserialization. The Http response has the status code and is in a good format. </p>"
  syntax:
    content: public class DecodeException extends HttpResponseException
- uid: com.azure.core.exception.HttpRequestException
  parent: com.azure.core.exception
  href: com.azure.core.exception.HttpRequestException.yml
  name: HttpRequestException
  nameWithType: HttpRequestException
  fullName: com.azure.core.exception.HttpRequestException
  type: Class
  summary: "<p>The exception occurred while attempting to connect a socket to a azure service address and port. Typically, the connection was refused remotely (e.g., no process is listening on the azure service address/port).</p>\r\n<p>These errors are safe to retry. </p>"
  syntax:
    content: public class HttpRequestException extends AzureException
- uid: com.azure.core.exception.HttpResponseException
  parent: com.azure.core.exception
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException
  nameWithType: HttpResponseException
  fullName: com.azure.core.exception.HttpResponseException
  type: Class
  summary: "<p>The exception thrown when an unsuccessful response is received with http status code (e.g. 3XX, 4XX, 5XX) from the service request. </p>"
  syntax:
    content: public class HttpResponseException extends AzureException
- uid: com.azure.core.exception.ResourceExistsException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ResourceExistsException.yml
  name: ResourceExistsException
  nameWithType: ResourceExistsException
  fullName: com.azure.core.exception.ResourceExistsException
  type: Class
  summary: "<p>The exception thrown when HTTP request tried to create an already existing resource with status code of 4XX, typically 412 conflict. </p>"
  syntax:
    content: public class ResourceExistsException extends HttpResponseException
- uid: com.azure.core.exception.ResourceModifiedException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ResourceModifiedException.yml
  name: ResourceModifiedException
  nameWithType: ResourceModifiedException
  fullName: com.azure.core.exception.ResourceModifiedException
  type: Class
  summary: "<p>The exception thrown for invalid resource modification with status code of 4XX, typically 409 Conflict. </p>"
  syntax:
    content: public class ResourceModifiedException extends HttpResponseException
- uid: com.azure.core.exception.ResourceNotFoundException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ResourceNotFoundException.yml
  name: ResourceNotFoundException
  nameWithType: ResourceNotFoundException
  fullName: com.azure.core.exception.ResourceNotFoundException
  type: Class
  summary: "<p>An error response, typically triggered by a 412 response (for update) or 404 (for get/post) </p>"
  syntax:
    content: public class ResourceNotFoundException extends HttpResponseException
- uid: com.azure.core.exception.ServiceResponseException
  parent: com.azure.core.exception
  href: com.azure.core.exception.ServiceResponseException.yml
  name: ServiceResponseException
  nameWithType: ServiceResponseException
  fullName: com.azure.core.exception.ServiceResponseException
  type: Class
  summary: "<p>A runtime exception indicating service response failure caused by one of the following scenarios: 1. The request was sent, but the client failed to understand the response. (Not in the right format, partial response etc.) 2. The connection may have timed out. These errors can be retried for idempotent or safe operations. </p>"
  syntax:
    content: public class ServiceResponseException extends AzureException
- uid: com.azure.core.exception.TooManyRedirectsException
  parent: com.azure.core.exception
  href: com.azure.core.exception.TooManyRedirectsException.yml
  name: TooManyRedirectsException
  nameWithType: TooManyRedirectsException
  fullName: com.azure.core.exception.TooManyRedirectsException
  type: Class
  summary: "<p>This exception is thrown when an HTTP request has reached the maximum number of redirect attempts with HTTP status code of 3XX.</p>\r\n<p></p>"
  syntax:
    content: public class TooManyRedirectsException extends HttpResponseException
