### YamlMime:ManagedReference
items:
- uid: com.azure.core.management.CloudException
  id: CloudException
  parent: com.azure.core.management
  children:
  - com.azure.core.management.CloudException.CloudException(String,HttpResponse)
  - com.azure.core.management.CloudException.CloudException(String,HttpResponse,CloudError)
  - com.azure.core.management.CloudException.toString()
  - com.azure.core.management.CloudException.value()
  href: com.azure.core.management.CloudException.yml
  langs:
  - java
  name: CloudException
  nameWithType: CloudException
  fullName: com.azure.core.management.CloudException
  type: Class
  source:
    remote: &o0
      path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
      branch: master
      repo: https://github.com/Azure/azure-sdk-for-java
    path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
    startLine: 11
  package: com.azure.core.management
  summary: "<p>Exception thrown for an invalid response with custom error information. </p>"
  syntax:
    content: public class CloudException extends HttpResponseException
  inheritance:
  - java.lang.Object
  - RuntimeException
  - com.azure.core.exception.AzureException
  - com.azure.core.exception.HttpResponseException
  inheritedMembers:
  - com.azure.core.exception.AzureException.AzureException(final String)
  - com.azure.core.exception.AzureException.AzureException(final String,final Throwable)
  - com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse)
  - com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse,final Object)
  - com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse,final Throwable)
  - com.azure.core.exception.HttpResponseException.response()
- uid: com.azure.core.management.CloudException.CloudException(String,HttpResponse)
  id: CloudException(String,HttpResponse)
  parent: com.azure.core.management.CloudException
  href: com.azure.core.management.CloudException.yml
  langs:
  - java
  name: CloudException(String message, HttpResponse response)
  nameWithType: CloudException.CloudException(String message, HttpResponse response)
  fullName: com.azure.core.management.CloudException.CloudException(String message, HttpResponse response)
  overload: com.azure.core.management.CloudException.CloudException*
  type: Constructor
  source:
    remote: *o0
    path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
    startLine: 22
  package: com.azure.core.management
  summary: "<p>Initializes a new instance of the CloudException class.</p>\r\n<p></p>"
  syntax:
    content: public CloudException(String message, HttpResponse response)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message or the response content if a message is not available </p>
    - id: response
      type: com.azure.core.http.HttpResponse
      description: <p>the HTTP response </p>
- uid: com.azure.core.management.CloudException.CloudException(String,HttpResponse,CloudError)
  id: CloudException(String,HttpResponse,CloudError)
  parent: com.azure.core.management.CloudException
  href: com.azure.core.management.CloudException.yml
  langs:
  - java
  name: CloudException(String message, HttpResponse response, CloudError body)
  nameWithType: CloudException.CloudException(String message, HttpResponse response, CloudError body)
  fullName: com.azure.core.management.CloudException.CloudException(String message, HttpResponse response, CloudError body)
  overload: com.azure.core.management.CloudException.CloudException*
  type: Constructor
  source:
    remote: *o0
    path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
    startLine: 33
  package: com.azure.core.management
  summary: "<p>Initializes a new instance of the CloudException class.</p>\r\n<p></p>"
  syntax:
    content: public CloudException(String message, HttpResponse response, CloudError body)
    parameters:
    - id: message
      type: "26831127"
      description: <p>the exception message or the response content if a message is not available </p>
    - id: response
      type: com.azure.core.http.HttpResponse
      description: <p>the HTTP response </p>
    - id: body
      type: com.azure.core.management.CloudError
      description: <p>the deserialized response body </p>
- uid: com.azure.core.management.CloudException.toString()
  id: toString()
  parent: com.azure.core.management.CloudException
  href: com.azure.core.management.CloudException.yml
  langs:
  - java
  name: toString()
  nameWithType: CloudException.toString()
  fullName: com.azure.core.management.CloudException.toString()
  overload: com.azure.core.management.CloudException.toString*
  type: Method
  source:
    remote: *o0
    path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
    startLine: 43
  package: com.azure.core.management
  syntax:
    content: public String toString()
    return:
      type: "26831127"
- uid: com.azure.core.management.CloudException.value()
  id: value()
  parent: com.azure.core.management.CloudException
  href: com.azure.core.management.CloudException.yml
  langs:
  - java
  name: value()
  nameWithType: CloudException.value()
  fullName: com.azure.core.management.CloudException.value()
  overload: com.azure.core.management.CloudException.value*
  type: Method
  source:
    remote: *o0
    path: sdk/core/azure-core-management/src/main/java/com/azure/core/management/CloudException.java
    startLine: 38
  package: com.azure.core.management
  syntax:
    content: public CloudError value()
    return:
      type: com.azure.core.management.CloudError
references:
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: com.azure.core.management.CloudException.CloudException*
  name: CloudException
  nameWithType: CloudException.CloudException
  fullName: com.azure.core.management.CloudException.CloudException
  package: com.azure.core.management
- uid: com.azure.core.management.CloudException.value*
  name: value
  nameWithType: CloudException.value
  fullName: com.azure.core.management.CloudException.value
  package: com.azure.core.management
- uid: com.azure.core.management.CloudException.toString*
  name: toString
  nameWithType: CloudException.toString
  fullName: com.azure.core.management.CloudException.toString
  package: com.azure.core.management
- uid: com.azure.core.exception.AzureException.AzureException(final String)
  parent: com.azure.core.exception.AzureException
  href: com.azure.core.exception.AzureException.yml
  name: AzureException(final String message)
  nameWithType: AzureException.AzureException(final String message)
  fullName: com.azure.core.exception.AzureException.AzureException(final String message)
  type: Constructor
  summary: "<p>Initializes a new instance of the AzureException class.</p>\r\n<p></p>"
  syntax:
    content: public AzureException(final String message)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message. </p>
- uid: com.azure.core.exception.AzureException.AzureException(final String,final Throwable)
  parent: com.azure.core.exception.AzureException
  href: com.azure.core.exception.AzureException.yml
  name: AzureException(final String message, final Throwable cause)
  nameWithType: AzureException.AzureException(final String message, final Throwable cause)
  fullName: com.azure.core.exception.AzureException.AzureException(final String message, final Throwable cause)
  type: Constructor
  summary: "<p>Initializes a new instance of the AzureException class.</p>\r\n<p></p>"
  syntax:
    content: public AzureException(final String message, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message. </p>
    - id: cause
      type: fa00b19f
      description: <p>the Throwable which caused the creation of this AzureException. </p>
- uid: com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse)
  parent: com.azure.core.exception.HttpResponseException
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException(final String message, final HttpResponse response)
  nameWithType: HttpResponseException.HttpResponseException(final String message, final HttpResponse response)
  fullName: com.azure.core.exception.HttpResponseException.HttpResponseException(final String message, final HttpResponse response)
  type: Constructor
  summary: "<p>Initializes a new instance of the HttpResponseException class.</p>\r\n<p></p>"
  syntax:
    content: public HttpResponseException(final String message, final HttpResponse response)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message or the response content if a message is not available </p>
    - id: response
      type: 93de0ef9com.azure.core.http.HttpResponse
      description: <p>the HTTP response </p>
- uid: com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse,final Object)
  parent: com.azure.core.exception.HttpResponseException
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException(final String message, final HttpResponse response, final Object value)
  nameWithType: HttpResponseException.HttpResponseException(final String message, final HttpResponse response, final Object value)
  fullName: com.azure.core.exception.HttpResponseException.HttpResponseException(final String message, final HttpResponse response, final Object value)
  type: Constructor
  summary: "<p>Initializes a new instance of the HTTPResponseException class.</p>\r\n<p></p>"
  syntax:
    content: public HttpResponseException(final String message, final HttpResponse response, final Object value)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message or the response content if a message is not available </p>
    - id: response
      type: 93de0ef9com.azure.core.http.HttpResponse
      description: <p>the HTTP response received from Azure service </p>
    - id: value
      type: 1b60ba29
      description: <p>the deserialized response value </p>
- uid: com.azure.core.exception.HttpResponseException.HttpResponseException(final String,final HttpResponse,final Throwable)
  parent: com.azure.core.exception.HttpResponseException
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException(final String message, final HttpResponse response, final Throwable cause)
  nameWithType: HttpResponseException.HttpResponseException(final String message, final HttpResponse response, final Throwable cause)
  fullName: com.azure.core.exception.HttpResponseException.HttpResponseException(final String message, final HttpResponse response, final Throwable cause)
  type: Constructor
  summary: "<p>Initializes a new instance of the HttpResponseException class.</p>\r\n<p></p>"
  syntax:
    content: public HttpResponseException(final String message, final HttpResponse response, final Throwable cause)
    parameters:
    - id: message
      type: 3d93591e
      description: <p>the exception message or the response content if a message is not available </p>
    - id: response
      type: 93de0ef9com.azure.core.http.HttpResponse
      description: <p>the HTTP response </p>
    - id: cause
      type: fa00b19f
      description: <p>the Throwable which caused the creation of this HttpResponseException </p>
- uid: com.azure.core.exception.HttpResponseException.response()
  parent: com.azure.core.exception.HttpResponseException
  href: com.azure.core.exception.HttpResponseException.yml
  name: response()
  nameWithType: HttpResponseException.response()
  fullName: com.azure.core.exception.HttpResponseException.response()
  type: Method
  syntax:
    content: public HttpResponse response()
    return:
      type: com.azure.core.http.HttpResponse
      description: <p>information about the associated HTTP response </p>
- uid: com.azure.core.exception.HttpResponseException
  parent: com.azure.core.exception
  href: com.azure.core.exception.HttpResponseException.yml
  name: HttpResponseException
  nameWithType: HttpResponseException
  fullName: com.azure.core.exception.HttpResponseException
  type: Class
  summary: "<p>The exception thrown when an unsuccessful response is received with http status code (e.g. 3XX, 4XX, 5XX) from the service request. </p>"
  syntax:
    content: public class HttpResponseException
- uid: com.azure.core.http.HttpResponse
  parent: com.azure.core.http
  href: com.azure.core.http.HttpResponse.yml
  name: HttpResponse
  nameWithType: HttpResponse
  fullName: com.azure.core.http.HttpResponse
  type: Class
  summary: "<p>The type representing response of <xref uid=\"com.azure.core.http.HttpRequest\" data-throw-if-not-resolved=\"false\">HttpRequest</xref>. </p>"
  syntax:
    content: public class HttpResponse
- uid: com.azure.core.management.CloudError
  parent: com.azure.core.management
  href: com.azure.core.management.CloudError.yml
  name: CloudError
  nameWithType: CloudError
  fullName: com.azure.core.management.CloudError
  type: Class
  summary: "<p>An instance of this class provides additional information about an http error response. </p>"
  syntax:
    content: public class CloudError
