### YamlMime:JavaMember
uid: "com.azure.core.http.netty.implementation.HttpProxyExceptionHandler.exceptionCaught*"
fullName: "com.azure.core.http.netty.implementation.HttpProxyExceptionHandler.exceptionCaught"
name: "exceptionCaught"
nameWithType: "HttpProxyExceptionHandler.exceptionCaught"
members:
- uid: "com.azure.core.http.netty.implementation.HttpProxyExceptionHandler.exceptionCaught(io.netty.channel.ChannelHandlerContext,java.lang.Throwable)"
  fullName: "com.azure.core.http.netty.implementation.HttpProxyExceptionHandler.exceptionCaught(ChannelHandlerContext ctx, Throwable cause)"
  name: "exceptionCaught(ChannelHandlerContext ctx, Throwable cause)"
  nameWithType: "HttpProxyExceptionHandler.exceptionCaught(ChannelHandlerContext ctx, Throwable cause)"
  overridden: "io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(io.netty.channel.ChannelHandlerContext,java.lang.Throwable)"
  parameters:
  - name: "ctx"
    type: "<xref href=\"io.netty.channel.ChannelHandlerContext?alt=io.netty.channel.ChannelHandlerContext&text=ChannelHandlerContext\" data-throw-if-not-resolved=\"False\" />"
  - name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause)"
type: "method"
metadata: {}
package: "com.azure.core.http.netty.implementation"
artifact: com.azure:azure-core-http-netty:1.9.1
