### YamlMime:JavaType
uid: "com.azure.core.exception.ServiceResponseException"
fullName: "com.azure.core.exception.ServiceResponseException"
name: "ServiceResponseException"
nameWithType: "ServiceResponseException"
summary: "A runtime exception indicating service response failure caused by one of the following scenarios:\n\n1.  The request was sent, but the client failed to understand the response."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class ServiceResponseException extends AzureException"
constructors:
- uid: "com.azure.core.exception.ServiceResponseException.ServiceResponseException(java.lang.String)"
  fullName: "com.azure.core.exception.ServiceResponseException.ServiceResponseException(String message)"
  name: "ServiceResponseException(String message)"
  nameWithType: "ServiceResponseException.ServiceResponseException(String message)"
  summary: "Initializes a new instance of the Service<wbr>Response<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available"
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ServiceResponseException(String message)"
  desc: "Initializes a new instance of the ServiceResponseException class."
- uid: "com.azure.core.exception.ServiceResponseException.ServiceResponseException(java.lang.String,java.lang.Throwable)"
  fullName: "com.azure.core.exception.ServiceResponseException.ServiceResponseException(String message, Throwable cause)"
  name: "ServiceResponseException(String message, Throwable cause)"
  nameWithType: "ServiceResponseException.ServiceResponseException(String message, Throwable cause)"
  summary: "Initializes a new instance of the Service<wbr>Response<wbr>Exception class."
  parameters:
  - description: "the exception message."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the Throwable which caused the creation of this ServiceResponseException."
    name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ServiceResponseException(String message, Throwable cause)"
  desc: "Initializes a new instance of the ServiceResponseException class."
type: "class"
desc: "A runtime exception indicating service response failure caused by one of the following scenarios:\n\n1.  The request was sent, but the client failed to understand the response. (Not in the right format, partial response, etc.).\n2.  The connection may have timed out. These errors can be retried for idempotent or safe operations."
metadata: {}
package: "com.azure.core.exception"
artifact: com.azure:azure-core:1.31.0
