### YamlMime:JavaType
uid: "com.azure.resourcemanager.compute.models.ApiErrorException"
fullName: "com.azure.resourcemanager.compute.models.ApiErrorException"
name: "ApiErrorException"
nameWithType: "ApiErrorException"
summary: "Exception thrown for an invalid response with Api<wbr>Error information."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.HttpResponseException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.management.exception.ManagementException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "com.azure.core.exception.HttpResponseException.getResponse()"
- "com.azure.core.management.exception.ManagementException.getValue()"
- "com.azure.core.management.exception.ManagementException.toString()"
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
syntax: "public final class ApiErrorException extends ManagementException"
constructors:
- uid: "com.azure.resourcemanager.compute.models.ApiErrorException.ApiErrorException(java.lang.String,com.azure.core.http.HttpResponse)"
  fullName: "com.azure.resourcemanager.compute.models.ApiErrorException.ApiErrorException(String message, HttpResponse response)"
  name: "ApiErrorException(String message, HttpResponse response)"
  nameWithType: "ApiErrorException.ApiErrorException(String message, HttpResponse response)"
  summary: "Initializes a new instance of the Api<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ApiErrorException(String message, HttpResponse response)"
  desc: "Initializes a new instance of the ApiErrorException class."
- uid: "com.azure.resourcemanager.compute.models.ApiErrorException.ApiErrorException(java.lang.String,com.azure.core.http.HttpResponse,com.azure.resourcemanager.compute.models.ApiError)"
  fullName: "com.azure.resourcemanager.compute.models.ApiErrorException.ApiErrorException(String message, HttpResponse response, ApiError value)"
  name: "ApiErrorException(String message, HttpResponse response, ApiError value)"
  nameWithType: "ApiErrorException.ApiErrorException(String message, HttpResponse response, ApiError value)"
  summary: "Initializes a new instance of the Api<wbr>Error<wbr>Exception class."
  parameters:
  - description: "the exception message or the response content if a message is not available."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "the HTTP response."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "the deserialized response value."
    name: "value"
    type: "<xref href=\"com.azure.resourcemanager.compute.models.ApiError?alt=com.azure.resourcemanager.compute.models.ApiError&text=ApiError\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public ApiErrorException(String message, HttpResponse response, ApiError value)"
  desc: "Initializes a new instance of the ApiErrorException class."
methods:
- uid: "com.azure.resourcemanager.compute.models.ApiErrorException.getValue()"
  fullName: "com.azure.resourcemanager.compute.models.ApiErrorException.getValue()"
  name: "getValue()"
  nameWithType: "ApiErrorException.getValue()"
  overridden: "com.azure.core.management.exception.ManagementException.getValue()"
  syntax: "public ApiError getValue()"
  returns:
    type: "<xref href=\"com.azure.resourcemanager.compute.models.ApiError?alt=com.azure.resourcemanager.compute.models.ApiError&text=ApiError\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "Exception thrown for an invalid response with ApiError information."
metadata: {}
package: "com.azure.resourcemanager.compute.models"
artifact: com.azure.resourcemanager:azure-resourcemanager-compute:2.16.0
