### YamlMime:JavaType
uid: "com.azure.core.exception.HttpResponseException"
fullName: "com.azure.core.exception.HttpResponseException"
name: "HttpResponseException"
nameWithType: "HttpResponseException"
summary: "The exception thrown when an unsuccessful response is received with http status code (e.<wbr>g."
inheritances:
- "<xref href=\"java.lang.Object?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Throwable?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.Exception?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"java.lang.RuntimeException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
- "<xref href=\"com.azure.core.exception.AzureException?displayProperty=fullName\" data-throw-if-not-resolved=\"False\" />"
inheritedMembers:
- "java.lang.Object.clone()"
- "java.lang.Object.equals(java.lang.Object)"
- "java.lang.Object.finalize()"
- "java.lang.Object.getClass()"
- "java.lang.Object.hashCode()"
- "java.lang.Object.notify()"
- "java.lang.Object.notifyAll()"
- "java.lang.Object.wait()"
- "java.lang.Object.wait(long)"
- "java.lang.Object.wait(long,int)"
- "java.lang.Throwable.addSuppressed(java.lang.Throwable)"
- "java.lang.Throwable.fillInStackTrace()"
- "java.lang.Throwable.getCause()"
- "java.lang.Throwable.getLocalizedMessage()"
- "java.lang.Throwable.getMessage()"
- "java.lang.Throwable.getStackTrace()"
- "java.lang.Throwable.getSuppressed()"
- "java.lang.Throwable.initCause(java.lang.Throwable)"
- "java.lang.Throwable.printStackTrace()"
- "java.lang.Throwable.printStackTrace(java.io.PrintStream)"
- "java.lang.Throwable.printStackTrace(java.io.PrintWriter)"
- "java.lang.Throwable.setStackTrace(java.lang.StackTraceElement[])"
- "java.lang.Throwable.toString()"
syntax: "public class HttpResponseException extends AzureException"
constructors:
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(com.azure.core.http.HttpResponse)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(HttpResponse response)"
  name: "HttpResponseException(HttpResponse response)"
  nameWithType: "HttpResponseException.HttpResponseException(HttpResponse response)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(HttpResponse response)"
  desc: "Initializes a new instance of the HttpResponseException class."
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(com.azure.core.http.HttpResponse,java.lang.Throwable)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(HttpResponse response, Throwable cause)"
  name: "HttpResponseException(HttpResponse response, Throwable cause)"
  nameWithType: "HttpResponseException.HttpResponseException(HttpResponse response, Throwable cause)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"java.lang.Throwable\" data-throw-if-not-resolved=\"false\" data-raw-source=\"Throwable\"></xref> which caused the creation of this exception."
    name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(HttpResponse response, Throwable cause)"
  desc: "Initializes a new instance of the HttpResponseException class."
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(java.lang.String,com.azure.core.http.HttpResponse)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(String message, HttpResponse response)"
  name: "HttpResponseException(String message, HttpResponse response)"
  nameWithType: "HttpResponseException.HttpResponseException(String message, HttpResponse response)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The exception message."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(String message, HttpResponse response)"
  desc: "Initializes a new instance of the HttpResponseException class."
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(java.lang.String,com.azure.core.http.HttpResponse,java.lang.Object)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(String message, HttpResponse response, Object value)"
  name: "HttpResponseException(String message, HttpResponse response, Object value)"
  nameWithType: "HttpResponseException.HttpResponseException(String message, HttpResponse response, Object value)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The exception message."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The deserialized response value."
    name: "value"
    type: "<xref href=\"java.lang.Object?alt=java.lang.Object&text=Object\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(String message, HttpResponse response, Object value)"
  desc: "Initializes a new instance of the HttpResponseException class."
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(java.lang.String,com.azure.core.http.HttpResponse,java.lang.Throwable)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(String message, HttpResponse response, Throwable cause)"
  name: "HttpResponseException(String message, HttpResponse response, Throwable cause)"
  nameWithType: "HttpResponseException.HttpResponseException(String message, HttpResponse response, Throwable cause)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The exception message."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"java.lang.Throwable\" data-throw-if-not-resolved=\"false\" data-raw-source=\"Throwable\"></xref> which caused the creation of this exception."
    name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(String message, HttpResponse response, Throwable cause)"
  desc: "Initializes a new instance of the HttpResponseException class."
- uid: "com.azure.core.exception.HttpResponseException.HttpResponseException(java.lang.String,com.azure.core.http.HttpResponse,java.lang.Throwable,boolean,boolean)"
  fullName: "com.azure.core.exception.HttpResponseException.HttpResponseException(String message, HttpResponse response, Throwable cause, boolean enableSuppression, boolean writableStackTrace)"
  name: "HttpResponseException(String message, HttpResponse response, Throwable cause, boolean enableSuppression, boolean writableStackTrace)"
  nameWithType: "HttpResponseException.HttpResponseException(String message, HttpResponse response, Throwable cause, boolean enableSuppression, boolean writableStackTrace)"
  summary: "Initializes a new instance of the Http<wbr>Response<wbr>Exception class."
  parameters:
  - description: "The exception message."
    name: "message"
    type: "<xref href=\"java.lang.String?alt=java.lang.String&text=String\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    name: "response"
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
  - description: "The <xref uid=\"java.lang.Throwable\" data-throw-if-not-resolved=\"false\" data-raw-source=\"Throwable\"></xref> which caused the creation of this exception."
    name: "cause"
    type: "<xref href=\"java.lang.Throwable?alt=java.lang.Throwable&text=Throwable\" data-throw-if-not-resolved=\"False\" />"
  - description: "Whether suppression is enabled or disabled."
    name: "enableSuppression"
    type: "<xref href=\"boolean?alt=boolean&text=boolean\" data-throw-if-not-resolved=\"False\" />"
  - description: "Whether the exception stack trace will be filled in."
    name: "writableStackTrace"
    type: "<xref href=\"boolean?alt=boolean&text=boolean\" data-throw-if-not-resolved=\"False\" />"
  syntax: "public HttpResponseException(String message, HttpResponse response, Throwable cause, boolean enableSuppression, boolean writableStackTrace)"
  desc: "Initializes a new instance of the HttpResponseException class."
methods:
- uid: "com.azure.core.exception.HttpResponseException.getResponse()"
  fullName: "com.azure.core.exception.HttpResponseException.getResponse()"
  name: "getResponse()"
  nameWithType: "HttpResponseException.getResponse()"
  syntax: "public HttpResponse getResponse()"
  returns:
    description: "The <xref uid=\"com.azure.core.http.HttpResponse\" data-throw-if-not-resolved=\"false\" data-raw-source=\"HttpResponse\"></xref> received that is associated to the exception."
    type: "<xref href=\"com.azure.core.http.HttpResponse?alt=com.azure.core.http.HttpResponse&text=HttpResponse\" data-throw-if-not-resolved=\"False\" />"
- uid: "com.azure.core.exception.HttpResponseException.getValue()"
  fullName: "com.azure.core.exception.HttpResponseException.getValue()"
  name: "getValue()"
  nameWithType: "HttpResponseException.getValue()"
  syntax: "public Object getValue()"
  returns:
    description: "The deserialized HTTP response value."
    type: "<xref href=\"java.lang.Object?alt=java.lang.Object&text=Object\" data-throw-if-not-resolved=\"False\" />"
type: "class"
desc: "The exception thrown when an unsuccessful response is received with http status code (e.g. 3XX, 4XX, 5XX) from the service request."
metadata: {}
package: "com.azure.core.exception"
artifact: com.azure:azure-core:1.31.0
