### YamlMime:ManagedReference
items:
- uid: system.fabric.exception._fabric_exception
  id: _fabric_exception
  parent: system.fabric.exception
  children:
  - system.fabric.exception._fabric_exception.FabricException()
  - system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
  - system.fabric.exception._fabric_exception.FabricException(String)
  - system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)
  - system.fabric.exception._fabric_exception.FabricException(String,Throwable)
  - system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)
  - system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)
  - system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)
  - system.fabric.exception._fabric_exception.FabricException(Throwable)
  - system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)
  - system.fabric.exception._fabric_exception.getErrorCode()
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException
  nameWithType: FabricException
  fullName: system.fabric.exception.FabricException
  type: Class
  source:
    remote: &o0
      path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
      branch: master
      repo: https://msazure.visualstudio.com/One/_git/sf-java
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 4
  package: system.fabric.exception
  syntax:
    content: public class FabricException
  inheritance:
  - java.lang.Object
  - RuntimeException
- uid: system.fabric.exception._fabric_exception.FabricException()
  id: FabricException()
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException()
  nameWithType: FabricException.FabricException()
  fullName: system.fabric.exception.FabricException.FabricException()
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 12
  package: system.fabric.exception
  syntax:
    content: public FabricException()
- uid: system.fabric.exception._fabric_exception.FabricException(FabricErrorCode)
  id: FabricException(FabricErrorCode)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(FabricErrorCode errorCode)
  nameWithType: FabricException.FabricException(FabricErrorCode errorCode)
  fullName: system.fabric.exception.FabricException.FabricException(FabricErrorCode errorCode)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 16
  package: system.fabric.exception
  syntax:
    content: public FabricException(FabricErrorCode errorCode)
    parameters:
    - id: errorCode
      type: system.fabric._fabric_error_code
- uid: system.fabric.exception._fabric_exception.FabricException(String)
  id: FabricException(String)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message)
  nameWithType: FabricException.FabricException(String message)
  fullName: system.fabric.exception.FabricException.FabricException(String message)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 20
  package: system.fabric.exception
  syntax:
    content: public FabricException(String message)
    parameters:
    - id: message
      type: "26831127"
- uid: system.fabric.exception._fabric_exception.FabricException(String,FabricErrorCode)
  id: FabricException(String,FabricErrorCode)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message, FabricErrorCode errorCode)
  nameWithType: FabricException.FabricException(String message, FabricErrorCode errorCode)
  fullName: system.fabric.exception.FabricException.FabricException(String message, FabricErrorCode errorCode)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 25
  package: system.fabric.exception
  syntax:
    content: public FabricException(String message, FabricErrorCode errorCode)
    parameters:
    - id: message
      type: "26831127"
    - id: errorCode
      type: system.fabric._fabric_error_code
- uid: system.fabric.exception._fabric_exception.FabricException(String,Throwable)
  id: FabricException(String,Throwable)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message, Throwable cause)
  nameWithType: FabricException.FabricException(String message, Throwable cause)
  fullName: system.fabric.exception.FabricException.FabricException(String message, Throwable cause)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 30
  package: system.fabric.exception
  syntax:
    content: public FabricException(String message, Throwable cause)
    parameters:
    - id: message
      type: "26831127"
    - id: cause
      type: a04fafd7
- uid: system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean)
  id: FabricException(String,Throwable,boolean,boolean)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  nameWithType: FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  fullName: system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 50
  package: system.fabric.exception
  syntax:
    content: protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace)
    parameters:
    - id: message
      type: "26831127"
    - id: cause
      type: a04fafd7
    - id: enableSuppression
      type: 4fc6e284
    - id: writableStackTrace
      type: 4fc6e284
- uid: system.fabric.exception._fabric_exception.FabricException(String,Throwable,boolean,boolean,FabricErrorCode)
  id: FabricException(String,Throwable,boolean,boolean,FabricErrorCode)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)
  nameWithType: FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)
  fullName: system.fabric.exception.FabricException.FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 55
  package: system.fabric.exception
  syntax:
    content: protected FabricException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace, FabricErrorCode errorCode)
    parameters:
    - id: message
      type: "26831127"
    - id: cause
      type: a04fafd7
    - id: enableSuppression
      type: 4fc6e284
    - id: writableStackTrace
      type: 4fc6e284
    - id: errorCode
      type: system.fabric._fabric_error_code
- uid: system.fabric.exception._fabric_exception.FabricException(String,Throwable,FabricErrorCode)
  id: FabricException(String,Throwable,FabricErrorCode)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(String message, Throwable cause, FabricErrorCode errorCode)
  nameWithType: FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)
  fullName: system.fabric.exception.FabricException.FabricException(String message, Throwable cause, FabricErrorCode errorCode)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 35
  package: system.fabric.exception
  syntax:
    content: public FabricException(String message, Throwable cause, FabricErrorCode errorCode)
    parameters:
    - id: message
      type: "26831127"
    - id: cause
      type: a04fafd7
    - id: errorCode
      type: system.fabric._fabric_error_code
- uid: system.fabric.exception._fabric_exception.FabricException(Throwable)
  id: FabricException(Throwable)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(Throwable cause)
  nameWithType: FabricException.FabricException(Throwable cause)
  fullName: system.fabric.exception.FabricException.FabricException(Throwable cause)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 40
  package: system.fabric.exception
  syntax:
    content: public FabricException(Throwable cause)
    parameters:
    - id: cause
      type: a04fafd7
- uid: system.fabric.exception._fabric_exception.FabricException(Throwable,FabricErrorCode)
  id: FabricException(Throwable,FabricErrorCode)
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: FabricException(Throwable cause, FabricErrorCode errorCode)
  nameWithType: FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)
  fullName: system.fabric.exception.FabricException.FabricException(Throwable cause, FabricErrorCode errorCode)
  overload: system.fabric.exception._fabric_exception.FabricException*
  type: Constructor
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 45
  package: system.fabric.exception
  syntax:
    content: public FabricException(Throwable cause, FabricErrorCode errorCode)
    parameters:
    - id: cause
      type: a04fafd7
    - id: errorCode
      type: system.fabric._fabric_error_code
- uid: system.fabric.exception._fabric_exception.getErrorCode()
  id: getErrorCode()
  parent: system.fabric.exception._fabric_exception
  href: system.fabric.exception._fabric_exception.yml
  langs:
  - java
  name: getErrorCode()
  nameWithType: FabricException.getErrorCode()
  fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode()
  overload: system.fabric.exception._fabric_exception.getErrorCode*
  type: Method
  source:
    remote: *o0
    path: src/prod/src/java/system.fabric/src/system/fabric/exception/FabricException.java
    startLine: 65
  package: system.fabric.exception
  syntax:
    content: public FabricErrorCode getErrorCode()
    return:
      type: system.fabric._fabric_error_code
references:
- uid: system.fabric.exception._fabric_exception.FabricException*
  name: FabricException
  nameWithType: FabricException.FabricException
  fullName: system.fabric.exception.FabricException.FabricException
  package: system.fabric.exception
- uid: "26831127"
  spec.java:
  - name: String
    fullName: String
- uid: a04fafd7
  spec.java:
  - name: Throwable
    fullName: Throwable
- uid: system.fabric.exception._fabric_exception.getErrorCode*
  name: getErrorCode
  nameWithType: FabricException.getErrorCode
  fullName: FabricErrorCode system.fabric.exception.FabricException.getErrorCode
  package: system.fabric.exception
- uid: 4fc6e284
  spec.java:
  - name: boolean
    fullName: boolean
- uid: microsoft.servicefabric.actors._actor_concurrency_lock_timeout_exception
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._actor_concurrency_lock_timeout_exception.yml
  name: ActorConcurrencyLockTimeoutException
  nameWithType: ActorConcurrencyLockTimeoutException
  fullName: microsoft.servicefabric.actors.ActorConcurrencyLockTimeoutException
  type: Class
  summary: <p>Exception thrown by actor runtime when runtime cannot acquire the turn based concurrency lock to dispatch the method. </p>
  syntax:
    content: public class ActorConcurrencyLockTimeoutException extends FabricException
- uid: microsoft.servicefabric.actors._fabric_exception_wrapper
- uid: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._reentrancy_mode_disallowed_exception.yml
  name: ReentrancyModeDisallowedException
  nameWithType: ReentrancyModeDisallowedException
  fullName: microsoft.servicefabric.actors.ReentrancyModeDisallowedException
  type: Class
  summary: <p>Exception thrown by actor runtime when reentrant call is made for an actor and its <xref uid="microsoft.servicefabric.actors._reentrancy_mode" data-throw-if-not-resolved="false">ReentrancyMode</xref> is set to <xref uid="microsoft.servicefabric.actors._reentrancy_mode.Disallowed" data-throw-if-not-resolved="false">ReentrancyMode#Disallowed</xref>. </p>
  syntax:
    content: public class ReentrancyModeDisallowedException
- uid: microsoft.servicefabric.actors._reminder_not_found_exception
  parent: microsoft.servicefabric.actors
  href: microsoft.servicefabric.actors._reminder_not_found_exception.yml
  name: ReminderNotFoundException
  nameWithType: ReminderNotFoundException
  fullName: microsoft.servicefabric.actors.ReminderNotFoundException
  type: Class
  summary: <p>Exception thrown by actor runtime when a specified reminder is not found for the actor. </p>
  syntax:
    content: public class ReminderNotFoundException
- uid: system.fabric.exception._duplicate_message_exception
  parent: system.fabric.exception
  href: system.fabric.exception._duplicate_message_exception.yml
  name: DuplicateMessageException
  nameWithType: DuplicateMessageException
  fullName: system.fabric.exception.DuplicateMessageException
  type: Class
  summary: <p>Exception indicates that Actor recieved Duplicate Message </p>
  syntax:
    content: public class DuplicateMessageException extends FabricException
- uid: system.fabric.exception._fabric_backup_directory_not_empty_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_backup_directory_not_empty_exception.yml
  name: FabricBackupDirectoryNotEmptyException
  nameWithType: FabricBackupDirectoryNotEmptyException
  fullName: system.fabric.exception.FabricBackupDirectoryNotEmptyException
  type: Class
  summary: <p>The exception that is thrown when the user provided backup directory is not empty. </p>
  syntax:
    content: public class FabricBackupDirectoryNotEmptyException extends FabricException
- uid: system.fabric.exception._fabric_backup_in_progress_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_backup_in_progress_exception.yml
  name: FabricBackupInProgressException
  nameWithType: FabricBackupInProgressException
  fullName: system.fabric.exception.FabricBackupInProgressException
  type: Class
  summary: <p>The exception that is thrown when an attempt is made to create a backup when a previous backup is in progress. </p>
  syntax:
    content: public class FabricBackupInProgressException extends FabricException
- uid: system.fabric.exception._fabric_cannot_connect_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_cannot_connect_exception.yml
  name: FabricCannotConnectException
  nameWithType: FabricCannotConnectException
  fullName: system.fabric.exception.FabricCannotConnectException
  type: Class
  syntax:
    content: public class FabricCannotConnectException extends FabricException
- uid: system.fabric.exception._fabric_chaos_already_running_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_chaos_already_running_exception.yml
  name: FabricChaosAlreadyRunningException
  nameWithType: FabricChaosAlreadyRunningException
  fullName: system.fabric.exception.FabricChaosAlreadyRunningException
  type: Class
  summary: <p>The exception that is thrown when an instance of Chaos is already running </p>
  syntax:
    content: public class FabricChaosAlreadyRunningException extends FabricException
- uid: system.fabric.exception._fabric_connection_denied_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_connection_denied_exception.yml
  name: FabricConnectionDeniedException
  nameWithType: FabricConnectionDeniedException
  fullName: system.fabric.exception.FabricConnectionDeniedException
  type: Class
  summary: <p>The exception that is thrown when connection is denied. </p>
  syntax:
    content: public class FabricConnectionDeniedException extends FabricException
- uid: system.fabric.exception._fabric_delete_backup_file_failed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_delete_backup_file_failed_exception.yml
  name: FabricDeleteBackupFileFailedException
  nameWithType: FabricDeleteBackupFileFailedException
  fullName: system.fabric.exception.FabricDeleteBackupFileFailedException
  type: Class
  syntax:
    content: public class FabricDeleteBackupFileFailedException extends FabricException
- uid: system.fabric.exception._fabric_element_already_exists_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_element_already_exists_exception.yml
  name: FabricElementAlreadyExistsException
  nameWithType: FabricElementAlreadyExistsException
  fullName: system.fabric.exception.FabricElementAlreadyExistsException
  type: Class
  syntax:
    content: public class FabricElementAlreadyExistsException extends FabricException
- uid: system.fabric.exception._fabric_element_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_element_not_found_exception.yml
  name: FabricElementNotFoundException
  nameWithType: FabricElementNotFoundException
  fullName: system.fabric.exception.FabricElementNotFoundException
  type: Class
  syntax:
    content: public class FabricElementNotFoundException extends FabricException
- uid: system.fabric.exception._fabric_endpoint_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_endpoint_not_found_exception.yml
  name: FabricEndpointNotFoundException
  nameWithType: FabricEndpointNotFoundException
  fullName: system.fabric.exception.FabricEndpointNotFoundException
  type: Class
  summary: <p>Exception indicating that the specified endpoint was not found. </p>
  syntax:
    content: public class FabricEndpointNotFoundException extends FabricException
- uid: system.fabric.exception._fabric_image_store_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_image_store_exception.yml
  name: FabricImageStoreException
  nameWithType: FabricImageStoreException
  fullName: system.fabric.exception.FabricImageStoreException
  type: Class
  syntax:
    content: public class FabricImageStoreException
- uid: system.fabric.exception._fabric_invalid_address_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_address_exception.yml
  name: FabricInvalidAddressException
  nameWithType: FabricInvalidAddressException
  fullName: system.fabric.exception.FabricInvalidAddressException
  type: Class
  summary: <p>The exception that is thrown when an address is not recognized by Service fabric. </p>
  syntax:
    content: public class FabricInvalidAddressException
- uid: system.fabric.exception._fabric_invalid_atomic_group_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_atomic_group_exception.yml
  name: FabricInvalidAtomicGroupException
  nameWithType: FabricInvalidAtomicGroupException
  fullName: system.fabric.exception.FabricInvalidAtomicGroupException
  type: Class
  syntax:
    content: public class FabricInvalidAtomicGroupException
- uid: system.fabric.exception._fabric_invalid_partition_key_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_partition_key_exception.yml
  name: FabricInvalidPartitionKeyException
  nameWithType: FabricInvalidPartitionKeyException
  fullName: system.fabric.exception.FabricInvalidPartitionKeyException
  type: Class
  syntax:
    content: public class FabricInvalidPartitionKeyException
- uid: system.fabric.exception._fabric_invalid_test_command_state_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_invalid_test_command_state_exception.yml
  name: FabricInvalidTestCommandStateException
  nameWithType: FabricInvalidTestCommandStateException
  fullName: system.fabric.exception.FabricInvalidTestCommandStateException
  type: Class
  summary: <p>The exception that is thrown when an operation is not valid for a test command in a particular state. </p>
  syntax:
    content: public class FabricInvalidTestCommandStateException
- uid: system.fabric.exception._fabric_key_not_found_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_key_not_found_exception.yml
  name: FabricKeyNotFoundException
  nameWithType: FabricKeyNotFoundException
  fullName: system.fabric.exception.FabricKeyNotFoundException
  type: Class
  syntax:
    content: public class FabricKeyNotFoundException
- uid: system.fabric.exception._fabric_message_too_large_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_message_too_large_exception.yml
  name: FabricMessageTooLargeException
  nameWithType: FabricMessageTooLargeException
  fullName: system.fabric.exception.FabricMessageTooLargeException
  type: Class
  syntax:
    content: public class FabricMessageTooLargeException
- uid: system.fabric.exception._fabric_missing_full_backup_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_missing_full_backup_exception.yml
  name: FabricMissingFullBackupException
  nameWithType: FabricMissingFullBackupException
  fullName: system.fabric.exception.FabricMissingFullBackupException
  type: Class
  summary: <p>The exception that is thrown when an attempt is made to create an incremental backup of the key-value store before an initial full backup is created. </p>
  syntax:
    content: public class FabricMissingFullBackupException
- uid: system.fabric.exception._fabric_node_primary_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_node_primary_exception.yml
  name: FabricNodePrimaryException
  nameWithType: FabricNodePrimaryException
  fullName: system.fabric.exception.FabricNodePrimaryException
  type: Class
  syntax:
    content: public class FabricNodePrimaryException
- uid: system.fabric.exception._fabric_not_primary_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_not_primary_exception.yml
  name: FabricNotPrimaryException
  nameWithType: FabricNotPrimaryException
  fullName: system.fabric.exception.FabricNotPrimaryException
  type: Class
  syntax:
    content: public class FabricNotPrimaryException
- uid: system.fabric.exception._fabric_not_readable_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_not_readable_exception.yml
  name: FabricNotReadableException
  nameWithType: FabricNotReadableException
  fullName: system.fabric.exception.FabricNotReadableException
  type: Class
  syntax:
    content: public class FabricNotReadableException
- uid: system.fabric.exception._fabric_object_closed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_object_closed_exception.yml
  name: FabricObjectClosedException
  nameWithType: FabricObjectClosedException
  fullName: system.fabric.exception.FabricObjectClosedException
  type: Class
  syntax:
    content: public class FabricObjectClosedException
- uid: system.fabric.exception._fabric_replication_operation_too_large_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_replication_operation_too_large_exception.yml
  name: FabricReplicationOperationTooLargeException
  nameWithType: FabricReplicationOperationTooLargeException
  fullName: system.fabric.exception.FabricReplicationOperationTooLargeException
  type: Class
  summary: <p>Exception indicating that the associated replication operation is larger than the configured limit </p>
  syntax:
    content: public class FabricReplicationOperationTooLargeException
- uid: system.fabric.exception._fabric_server_authentication_failed_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_server_authentication_failed_exception.yml
  name: FabricServerAuthenticationFailedException
  nameWithType: FabricServerAuthenticationFailedException
  fullName: system.fabric.exception.FabricServerAuthenticationFailedException
  type: Class
  summary: <p>The exception that is thrown when server authentication failed. </p>
  syntax:
    content: public class FabricServerAuthenticationFailedException
- uid: system.fabric.exception._fabric_test_command_operation_id_already_exists_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_test_command_operation_id_already_exists_exception.yml
  name: FabricTestCommandOperationIdAlreadyExistsException
  nameWithType: FabricTestCommandOperationIdAlreadyExistsException
  fullName: system.fabric.exception.FabricTestCommandOperationIdAlreadyExistsException
  type: Class
  summary: <p>The exception that is thrown when an the Test Command already exists (duplicate operationId) </p>
  syntax:
    content: public class FabricTestCommandOperationIdAlreadyExistsException
- uid: system.fabric.exception._fabric_transient_exception
  parent: system.fabric.exception
  href: system.fabric.exception._fabric_transient_exception.yml
  name: FabricTransientException
  nameWithType: FabricTransientException
  fullName: system.fabric.exception.FabricTransientException
  type: Class
  syntax:
    content: public class FabricTransientException
- uid: system.fabric.exception._invalid_reentrant_call_exception
  parent: system.fabric.exception
  href: system.fabric.exception._invalid_reentrant_call_exception.yml
  name: InvalidReentrantCallException
  nameWithType: InvalidReentrantCallException
  fullName: system.fabric.exception.InvalidReentrantCallException
  type: Class
  syntax:
    content: public class InvalidReentrantCallException
- uid: system.fabric.exception._path_too_long_exception
  parent: system.fabric.exception
  href: system.fabric.exception._path_too_long_exception.yml
  name: PathTooLongException
  nameWithType: PathTooLongException
  fullName: system.fabric.exception.PathTooLongException
  type: Class
  syntax:
    content: public class PathTooLongException
- uid: system.fabric.exception._reentrant_actor_invalid_state_exception
  parent: system.fabric.exception
  href: system.fabric.exception._reentrant_actor_invalid_state_exception.yml
  name: ReentrantActorInvalidStateException
  nameWithType: ReentrantActorInvalidStateException
  fullName: system.fabric.exception.ReentrantActorInvalidStateException
  type: Class
  syntax:
    content: public class ReentrantActorInvalidStateException
- uid: system.fabric.exception._unauthorized_access_exception
  parent: system.fabric.exception
  href: system.fabric.exception._unauthorized_access_exception.yml
  name: UnauthorizedAccessException
  nameWithType: UnauthorizedAccessException
  fullName: system.fabric.exception.UnauthorizedAccessException
  type: Class
  summary: <p>Indicates mismatch between access credentials passed while creating visitor client object and the expected credentials that visitor services expects. </p>
  syntax:
    content: public class UnauthorizedAccessException
- uid: system.fabric._fabric_error_code
  parent: system.fabric
  href: system.fabric._fabric_error_code.yml
  name: FabricErrorCode
  nameWithType: FabricErrorCode
  fullName: system.fabric.FabricErrorCode
  type: Enum
  syntax:
    content: public enum FabricErrorCode
